import { BrainCard, BrainExport } from "./types.js";

export function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "item"
  );
}

export function byType(cards: BrainCard[], type: string): BrainCard[] {
  return cards.filter((c) => c.type === type);
}

/** Tenta interpretar o content como JSON; null se não for. */
export function tryJson<T = unknown>(content: string): T | null {
  try {
    return JSON.parse(content) as T;
  } catch {
    return null;
  }
}

/** Se o content já começa com frontmatter YAML (---\n…\n---). */
export function hasFrontmatter(content: string): boolean {
  return /^---\s*\n[\s\S]*?\n---\s*(\n|$)/.test(content);
}

/** Escapa um valor escalar pra frontmatter YAML. */
export function yamlScalar(value: string): string {
  const v = value.replace(/\n/g, " ").trim();
  return /[:#"'{}\[\],&*?|<>=!%@`]/.test(v) ? JSON.stringify(v) : v;
}

const DEFAULT_SECTIONS: { type: string; title: string }[] = [
  { type: "instruction", title: "Instructions" },
  { type: "spec", title: "Specs (requirements)" },
  { type: "boundary", title: "Limites (Sempre / Perguntar antes / Nunca)" },
  { type: "rule", title: "Rules & Instructions" },
  { type: "memory", title: "Memory & Context" },
  { type: "knowledge", title: "Conhecimento" },
  { type: "prompt", title: "Prompts" },
  { type: "integration", title: "Integrations" },
];

/**
 * Corpo markdown neutro do Brain — base do AGENTS.md/CLAUDE.md/GEMINI.md/Copilot.
 * harness/skill/mcp/agent ficam de fora (viram arquivos próprios); demais viram seções.
 * @param sections lista opcional pra customizar quais tipos entram e em que ordem.
 */
export function renderMarkdown(
  brain: BrainExport,
  sections: { type: string; title: string }[] = DEFAULT_SECTIONS
): string {
  const lines: string[] = [];
  lines.push(`# ${brain.brain.name}`);
  if (brain.brain.description) lines.push(`\n> ${brain.brain.description}`);
  lines.push(
    `\n_Configuration generated by Origem. Adopt the rules, memory and knowledge below as your operating context._`
  );

  for (const section of sections) {
    const group = byType(brain.cards, section.type);
    if (group.length === 0) continue;
    lines.push(`\n\n## ${section.title}`);
    for (const card of group) {
      const folder = card.folder ? ` _(${card.folder})_` : "";
      lines.push(`\n### ${card.title}${folder}`);
      if (card.tags?.length) lines.push(`\`${card.tags.join("` `")}\``);
      lines.push(`\n${card.content}`);
    }
  }
  return lines.join("\n") + "\n";
}
